paths:
  dataset: "/home/ge.polymtl.ca/jemal/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg"
  sub_paths:
    img:
      - "sub-3902bottom/anat"
      - "sub-3902top/anat"
    masks:
      - "derivatives/labels/sub-3902bottom/anat/"
      - "derivatives/labels/sub-3902top/anat/"
  results: "/home/ge.polymtl.ca/jemal/data_nvme_jemal/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/monai/results"

data:
  slice_axis: 1

transformations:
  randaffine:
    proba: 0.8
    degrees: 40
    translation: [0.1, 0.1]
  normalize: true

training:
  batch_size: 2
  num_epochs: 150
  early_stopping_patience: 50
  early_stopping_epsilon: 0.0001
  learning_rate: 0.001
  eta_min: 0.00001
  train_set_size: 0.8
  val_set_size: 0.2
  optimizer: "Adam"

UNet:
  spatial_dims: 2
  in_channels: 1
  out_channels: 1
  channels: [16, 32, 64, 128]
  strides: [2, 2, 2]
  num_res_units: 2
  dropout: 0.3
  activation: "relu"
  normalisation: "batch"

postprocessing:
  remove_noise :
    apply: true
    threshold: 0.01
  remove_small :
    apply: true
    min_size: 3
